<?php
return array(
    'SpiffyDoctrine\Module'                                        => __DIR__ . '/Module.php',
    'SpiffyDoctrineTest\Doctrine\CliTest'                          => __DIR__ . '/tests/SpiffyDoctrineTest/Doctrine/CliTest.php',
    'SpiffyDoctrineTest\Assets\Entity\Test'                        => __DIR__ . '/tests/SpiffyDoctrineTest/Assets/Entity/Test.php',
    'SpiffyDoctrineTest\Authentication\Adapter\DoctrineEntityTest' => __DIR__ . '/tests/SpiffyDoctrineTest/Authentication/Adapter/DoctrineEntityTest.php',
    'SpiffyDoctrineTest\Framework\TestCase'                        => __DIR__ . '/tests/SpiffyDoctrineTest/Framework/TestCase.php',
    'SpiffyDoctrine\Paginator\Adapter\DqlQuery'                    => __DIR__ . '/src/SpiffyDoctrine/Paginator/Adapter/DqlQuery.php',
    'SpiffyDoctrine\Paginator\TreeWalker\CountSqlWalker'           => __DIR__ . '/src/SpiffyDoctrine/Paginator/TreeWalker/CountSqlWalker.php',
    'SpiffyDoctrine\Factory\EntityManager'                         => __DIR__ . '/src/SpiffyDoctrine/Factory/EntityManager.php',
    'SpiffyDoctrine\Factory\DocumentManager'                       => __DIR__ . '/src/SpiffyDoctrine/Factory/DocumentManager.php',
    'SpiffyDoctrine\Doctrine\ODM\MongoDB\DriverChain'              => __DIR__ . '/src/SpiffyDoctrine/Doctrine/ODM/MongoDB/DriverChain.php',
    'SpiffyDoctrine\Doctrine\ODM\MongoDB\Connection'               => __DIR__ . '/src/SpiffyDoctrine/Doctrine/ODM/MongoDB/Connection.php',
    'SpiffyDoctrine\Doctrine\ODM\MongoDB\Configuration'            => __DIR__ . '/src/SpiffyDoctrine/Doctrine/ODM/MongoDB/Configuration.php',
    'SpiffyDoctrine\Doctrine\Instance'                             => __DIR__ . '/src/SpiffyDoctrine/Doctrine/Instance.php',
    'SpiffyDoctrine\Doctrine\ORM\DriverChain'                      => __DIR__ . '/src/SpiffyDoctrine/Doctrine/ORM/DriverChain.php',
    'SpiffyDoctrine\Doctrine\ORM\Connection'                       => __DIR__ . '/src/SpiffyDoctrine/Doctrine/ORM/Connection.php',
    'SpiffyDoctrine\Doctrine\ORM\Configuration'                    => __DIR__ . '/src/SpiffyDoctrine/Doctrine/ORM/Configuration.php',
    'SpiffyDoctrine\Doctrine\Common\EventManager'                  => __DIR__ . '/src/SpiffyDoctrine/Doctrine/Common/EventManager.php',
    'SpiffyDoctrine\Validator\EntityExists'                        => __DIR__ . '/src/SpiffyDoctrine/Validator/EntityExists.php',
    'SpiffyDoctrine\Validator\NoEntityExists'                      => __DIR__ . '/src/SpiffyDoctrine/Validator/NoEntityExists.php',
    'SpiffyDoctrine\Validator\AbstractEntity'                      => __DIR__ . '/src/SpiffyDoctrine/Validator/AbstractEntity.php',
    'SpiffyDoctrine\Version'                                       => __DIR__ . '/src/SpiffyDoctrine/VERSION.php',
    'SpiffyDoctrine\Authentication\Adapter\DoctrineEntity'         => __DIR__ . '/src/SpiffyDoctrine/Authentication/Adapter/DoctrineEntity.php',
);