<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DoctrineModule\Validator\EntityExists'                        => __DIR__ . '/src/DoctrineModule/Validator/EntityExists.php',
    'DoctrineModule\Validator\AbstractEntity'                      => __DIR__ . '/src/DoctrineModule/Validator/AbstractEntity.php',
    'DoctrineModule\Validator\NoEntityExists'                      => __DIR__ . '/src/DoctrineModule/Validator/NoEntityExists.php',
    'DoctrineModule\Authentication\Adapter\DoctrineEntity'         => __DIR__ . '/src/DoctrineModule/Authentication/Adapter/DoctrineEntity.php',
    'DoctrineModule\Service\Service'                               => __DIR__ . '/src/DoctrineModule/Service/Service.php',
    'DoctrineModule\Doctrine\Instance'                             => __DIR__ . '/src/DoctrineModule/Doctrine/Instance.php',
    'DoctrineModule\Doctrine\Common\DriverChain'                   => __DIR__ . '/src/DoctrineModule/Doctrine/Common/DriverChain.php',
    'DoctrineModule\Doctrine\Common\EventManager'                  => __DIR__ . '/src/DoctrineModule/Doctrine/Common/EventManager.php',
    'DoctrineModule\Paginator\Adapter\DqlQuery'                    => __DIR__ . '/src/DoctrineModule/Paginator/Adapter/DqlQuery.php',
    'DoctrineModule\Paginator\TreeWalker\CountSqlWalker'           => __DIR__ . '/src/DoctrineModule/Paginator/TreeWalker/CountSqlWalker.php',
    'DoctrineModule\Version'                                       => __DIR__ . '/src/DoctrineModule/Version.php',
    'DoctrineModule\Module'                                        => __DIR__ . '/Module.php',
    'DoctrineModuleTest\Authentication\Adapter\DoctrineEntityTest' => __DIR__ . '/tests/SpiffyDoctrineTest/Authentication/Adapter/DoctrineEntityTest.php',
    'DoctrineModuleTest\Assets\Entity\Test'                        => __DIR__ . '/tests/SpiffyDoctrineTest/Assets/Entity/Test.php',
    'DoctrineModuleTest\Doctrine\CliTest'                          => __DIR__ . '/tests/SpiffyDoctrineTest/Doctrine/CliTest.php',
    'DoctrineModuleTest\Framework\TestCase'                        => __DIR__ . '/tests/SpiffyDoctrineTest/Framework/TestCase.php',
);