name: "Static Analysis"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

permissions:
  contents: read

jobs:
  static-analysis:
    permissions:
      contents: none
    name: "Static Analysis"
    uses: "doctrine/.github/.github/workflows/static-analysis.yml@1.4.1"
    with:
      php-version: '8.1'
